#ifndef LY_AERIALSHOTSETTINGBUNDLE54_GLOBAL_H
#define LY_AERIALSHOTSETTINGBUNDLE54_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LY_AERIALSHOTSETTINGBUNDLE54_LIBRARY)
    #define LY_AERIALSHOTSETTINGBUNDLE54SHARED_EXPORT Q_DECL_EXPORT
#else
    #define LY_AERIALSHOTSETTINGBUNDLE54SHARED_EXPORT Q_DECL_IMPORT
#endif

#endif
