#ifndef LY_POSITIONMANAGESERVICE_GLOBAL_H
#define LY_POSITIONMANAGESERVICE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LY_POSITIONMANAGESERVICE_LIBRARY)
#  define LY_POSITIONMANAGESERVICESHARED_EXPORT Q_DECL_EXPORT
#else
#  define LY_POSITIONMANAGESERVICESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif
