#ifndef LY_COMMANDUNITMANAGESERVICE_GLOBAL_H
#define LY_COMMANDUNITMANAGESERVICE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LY_COMMANDUNITMANAGESERVICE_LIBRARY)
    #define LY_COMMANDUNITMANAGESERVICESHARED_EXPORT Q_DECL_EXPORT
#else
    #define LY_COMMANDUNITMANAGESERVICESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif
