#ifndef LY_ZONEMANAGERSERVIVE_GLOBAL_H
#define LY_ZONEMANAGERSERVIVE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LY_ZONEMANAGERSERVIVE_LIBRARY)
#define LY_ZONEMANAGERSERVIVESHARED_EXPORT Q_DECL_EXPORT
#else
#define LY_ZONEMANAGERSERVIVESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif
