FIND_PATH(SDL2_INCLUDE_DIR SDL2/SDL.h
  "{INCLUDE}"
  "{LIB_DIR}/include"
  "${CMAKE_CURRENT_SOURCE_DIR}/../include"
  "${CMAKE_CURRENT_SOURCE_DIR}/../include/ffmpeg"
)

FIND_LIBRARY(SDL2_LIBRARY NAMES SDL2 PATHS
  "{LIB}"
  "{LIB_DIR}/lib"
  "${CMAKE_CURRENT_SOURCE_DIR}/../lib/SDL2"
  "${CMAKE_CURRENT_SOURCE_DIR}/../lib/ffmpeg"
)

IF (SDL2_INCLUDE_DIR AND SDL2_LIBRARY)
  SET(SDL2_FOUND TRUE)
ENDIF ()
