#ifndef LY_AGRIYSPRAYPRESCRIPTIONSERVICE_GLOBAL_H
#define LY_AGRIYSPRAYPRESCRIPTIONSERVICE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LY_AGRIYSPRAYPRESCRIPTIONSERVICE_LIBRARY)
#  define LY_AGRIYSPRAYPRESCRIPTIONSERVICESHARED_EXPORT Q_DECL_EXPORT
#else
#  define LY_AGRIYSPRAYPRESCRIPTIONSERVICESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif
