
#ifndef LY_AGROTASKMANAGESERVICE_GLOBAL_H
#define LY_AGROTASKMANAGESERVICE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LY_AGROTASKMANAGESERVICE_LIBRARY)
    #define LY_AGROTASKMANAGESERVICESHARED_EXPORT Q_DECL_EXPORT
#else
    #define LY_AGROTASKMANAGESERVICESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // LY_AGROTASKMANAGESERVICE_GLOBAL_H
