#ifndef LY_COLLABORATIVESEARCHSERVICE_GLOBAL_H
#define LY_COLLABORATIVESEARCHSERVICE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LY_COLLABORATIVESEARCHSERVICE_LIBRARY)
#  define LY_COLLABORATIVESEARCHSERVICESHARED_EXPORT Q_DECL_EXPORT
#else
#  define LY_COLLABORATIVESEARCHSERVICESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif
