#ifndef LY_AMMUNITIONMANAGESERVICE_GLOBAL_H
#define LY_AMMUNITIONMANAGESERVICE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LY_AMMUNITIONMANAGESERVICE_LIBRARY)
    #define LY_AMMUNITIONMANAGESERVICESHARED_EXPORT Q_DECL_EXPORT
#else
    #define LY_AMMUNITIONMANAGESERVICESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif
