#ifndef LY_INTELLECTIMAGESHANGBO_GLOBAL_H
#define LY_INTELLECTIMAGESHANGBO_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LY_INTELLECTIMAGESHANGBO_LIBRARY)
#  define LY_INTELLECTIMAGESHANGBOSHARED_EXPORT Q_DECL_EXPORT
#else
#  define LY_INTELLECTIMAGESHANGBOSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif
