#ifndef LY_UAVFLYCONTROL_MAVLINK_GLOBAL_H
#define LY_UAVFLYCONTROL_MAVLINK_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LY_UAVFLYCONTROL_MAVLINK_LIBRARY)
#  define LY_UAVFLYCONTROLSHARED_MAVLINK_EXPORT Q_DECL_EXPORT
#else
#  define LY_UAVFLYCONTROLSHARED_MAVLINK_EXPORT Q_DECL_IMPORT
#endif

#endif
