#ifndef LY_TASKMANAGESERVICE_GLOBAL_H
#define LY_TASKMANAGESERVICE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LY_TASKMANAGESERVICE_LIBRARY)
    #define LY_TASKMANAGESERVICESHARED_EXPORT Q_DECL_EXPORT
#else
    #define LY_TASKMANAGESERVICESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif
