#ifndef LY_AGRISOILANALYSISPREDICT_GLOBAL_h__
#define LY_AGRISOILANALYSISPREDICT_GLOBAL_h__

#include <QtCore/qglobal.h>

#if defined(LY_AGRISOILTESTINGANALYSIS_LIBRARY)
#  define LY_AGRISOILTESTINGANALYSISSHARED_EXPORT Q_DECL_EXPORT
#else
#  define LY_AGRISOILTESTINGANALYSISSHARED_EXPORT Q_DECL_IMPORT
#endif
#endif // LY_AGRISOILANALYSISPREDICT_GLOBAL_h__
