#ifndef LY_UAVFLYCONTROL_DJI_DOCK_GLOBAL_H
#define LY_UAVFLYCONTROL_DJI_DOCK_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LY_UAVFLYCONTROL_DJI_DOCK_LIBRARY)
#  define LY_UAVFLYCONTROL_DJI_DOCK_EXPORT Q_DECL_EXPORT
#else
#  define LY_UAVFLYCONTROL_DJI_DOCK_EXPORT Q_DECL_IMPORT
#endif

#endif
