#ifndef LY_IPLATFORMSTATEMONITORING_GLOBAL_H
#define LY_IPLATFORMSTATEMONITORING_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LY_IPLATFORMSTATEMONITORING_LIBRARY)
    #define LY_IPLATFORMSTATEMONITORINGSHARED_EXPORT Q_DECL_EXPORT
#else
    #define LY_IPLATFORMSTATEMONITORINGSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif
