#ifndef LY_UAVNAVIGATIONARMSHOTALONE54_GLOBAL_H
#define LY_UAVNAVIGATIONARMSHOTALONE54_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LY_UAVNAVIGATIONARMSHOTALONE54_LIBRARY)
    #define LY_UAVNAVIGATIONARMSHOTALONE54SHARED_EXPORT Q_DECL_EXPORT
#else
    #define LY_UAVNAVIGATIONARMSHOTALONE54SHARED_EXPORT Q_DECL_IMPORT
#endif
#define  USE_ALL_IMAGE
#endif
