#ifndef LY_ZONEMANAGER_GLOBAL_H
#define LY_ZONEMANAGER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LY_ZONEMANAGER_LIBRARY)
#define LY_ZONEMANAGERSHARED_EXPORT Q_DECL_EXPORT
#else
#define LY_ZONEMANAGERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif
