#ifndef LY_WEAPONMANAGESERVICE_GLOBAL_H
#define LY_WEAPONMANAGESERVICE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LY_WEAPONMANAGESERVICE_LIBRARY)
#  define LY_WEAPONMANAGESERVICESHARED_EXPORT Q_DECL_EXPORT
#else
#  define LY_WEAPONMANAGESERVICESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif
