#ifndef LYUCISPLUGINFRAMEWORK_GLOBAL_H
#define LYUCISPLUGINFRAMEWORK_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LYUCISPLUGINFRAMEWORK_LIBRARY)
    #define LYUCISPLUGINFRAMEWORKSHARED_EXPORT Q_DECL_EXPORT
#else
    #define LYUCISPLUGINFRAMEWORKSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif
