#ifndef LY_AGRIMULTISPECTRALSENSOR_GLOBAL_H_
#define LY_AGRIMULTISPECTRALSENSOR_GLOBAL_H_
 
#include <QtCore/qglobal.h>

#if defined(LY_AGRIMULTISPECTRALSENSOR_LIBRARY)
#  define LY_AGRIMULTISPECTRALSENSORSHARED_EXPORT Q_DECL_EXPORT
#else
#  define LY_AGRIMULTISPECTRALSENSORSHARED_EXPORT Q_DECL_IMPORT
#endif
#endif  // LY_AgriMultispectralSensor_global_H