#ifndef LY_UAVREALTIMESTATEMANAGESERVICE_GLOBAL_H
#define LY_UAVREALTIMESTATEMANAGESERVICE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LY_UAVREALTIMESTATEMANAGESERVICE_LIBRARY)
#  define LY_UAVREALTIMESTATEMANAGESERVICESHARED_EXPORT Q_DECL_EXPORT
#else
#  define LY_UAVREALTIMESTATEMANAGESERVICESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif
