#ifndef LY_SCENARIOSREPLAY_GLOBAL_H
#define LY_SCENARIOSREPLAY_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LY_SCENARIOSREPLAY_LIBRARY)
#  define LY_SCENARIOSREPLAYSHARED_EXPORT Q_DECL_EXPORT
#else
#  define LY_SCENARIOSREPLAYSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif
