
#ifndef LY_AGRICULTUREHOMEPAGE_GLOBAL_H
#define LY_AGRICULTUREHOMEPAGE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LY_AGRICULTUREHOMEPAGE_LIBRARY)
#define LY_AGRICULTUREHOMEPAGESHARED_EXPORT Q_DECL_EXPORT
#else
#define LY_AGRICULTUREHOMEPAGESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // LY_AGRICULTUREHOMEPAGE_GLOBAL_H
