#ifndef LY_AGRIDATAANALYSISPREDICT_GLOBAL_H_
#define LY_AGRIDATAANALYSISPREDICT_GLOBAL_H_
 
#include <QtCore/qglobal.h>

#if defined(LY_AGRIDATAANALYSISPREDICT_LIBRARY)
#  define LY_AGRIDATAANALYSISPREDICTSHARED_EXPORT Q_DECL_EXPORT
#else
#  define LY_AGRIDATAANALYSISPREDICTSHARED_EXPORT Q_DECL_IMPORT
#endif
#endif  // LY_AgriDataAnalysisPredict_global_H