#ifndef LY_AGRIRESTFULMANAGER_GLOBAL_H_
#define LY_AGRIRESTFULMANAGER_GLOBAL_H_
 
#include <QtCore/qglobal.h>

#if defined(LY_AGRIRESTFULMANAGER_LIBRARY)
#  define LY_AGRIRESTFULMANAGERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define LY_AGRIRESTFULMANAGERSHARED_EXPORT Q_DECL_IMPORT
#endif
#endif  // LY_AgriRestfulManager_global_H