#ifndef LY_SENSORMANAGESERVICE_GLOBAL_H
#define LY_SENSORMANAGESERVICE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LY_SENSORMANAGESERVICE_LIBRARY)
#  define LY_SENSORMANAGESERVICESHARED_EXPORT Q_DECL_EXPORT
#else
#  define LY_SENSORMANAGESERVICESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif
