#ifndef LY_MARKMANAGESERVICE_GLOBAL_H
#define LY_MARKMANAGESERVICE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LY_MARKMANAGESERVICE_LIBRARY)
    #define LY_MARKMANAGESERVICESHARED_EXPORT Q_DECL_EXPORT
#else
    #define LY_MARKMANAGESERVICESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif
