#ifndef LY_PROTOCOLPARSE_XYGSSERVER_GLOBAL_H
#define LY_PROTOCOLPARSE_XYGSSERVER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LY_PROTOCOLPARSE_XYGSSERVER_LIBRARY)
#  define LY_PROTOCOLPARSE_XYGSSERVERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define LY_PROTOCOLPARSE_XYGSSERVERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif
