#ifndef LY_TASKPLATMATCH_GLOBAL_H
#define LY_TASKPLATMATCH_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LY_TASKPLATMATCH_LIBRARY)
    #define LY_TASKPLATMATCHSHARED_EXPORT Q_DECL_EXPORT
#else
    #define LY_TASKPLATMATCHSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif
