
#ifndef LY_AGRIVIDEOPLAYER_LIBRARY
#define LY_AGRIVIDEOPLAYER_LIBRARY

#include <QtCore/qglobal.h>
#if defined(LY_AGRIVIDEOPLAYER_LIBRARY)
#define LY_AGRIVIDEOPLAYERSHARED_EXPORT Q_DECL_EXPORT
#else
#define LY_AGRIVIDEOPLAYERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // LY_AGRIVIDEOPLAYER_LIBRARY
