
#ifndef LY_VIDEOREALTIMEPREVIEW_GLOBAL_H
#define LY_VIDEOREALTIMEPREVIEW_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LY_VIDEOREALTIMEPREVIEW_LIBRARY)
#define LY_VIDEOREALTIMEPREVIEWSHARED_EXPORT Q_DECL_EXPORT
#else
#define LY_VIDEOREALTIMEPREVIEWSHARED_EXPORT Q_DECL_IMPORT
#endif
//#define  USE_BRIEF_CALAC
#define  USE_GRAPHICS_VIEW
#endif // LY_VIDEOREALTIMEPREVIEW_GLOBAL_H
