#include "DataManage/AgriMachineManager/AgriMachineManagerDecl.h"

RTTR_REGISTRATION
{
	rttr::registration::class_<AgriMachineBasicInfo>("AgriMachineBasicInfo")
		.constructor<>()
		.property("id", &AgriMachineBasicInfo::id)
			(rttr::metadata("display", "编号"))
		.property("guid", &AgriMachineBasicInfo::guid)
			(rttr::metadata("display", "uuid"))
		.property("domain", &AgriMachineBasicInfo::domain)
			(rttr::metadata("display", "领域"))
		.property("category", &AgriMachineBasicInfo::category)
			(rttr::metadata("display", "类别"))
		.property("type", &AgriMachineBasicInfo::type)
			(rttr::metadata("display", "类型"))
		.property("item", &AgriMachineBasicInfo::item)
			(rttr::metadata("display", "品目"))
		.property("name", &AgriMachineBasicInfo::name)
			(rttr::metadata("display", "名称"))
		.property("product_model", &AgriMachineBasicInfo::product_model)
			(rttr::metadata("display", "产品型号"))
		.property("manufacturer", &AgriMachineBasicInfo::manufacturer)
			(rttr::metadata("display", "厂家"))
		.property("count", &AgriMachineBasicInfo::count)
			(rttr::metadata("display", "数量"))
		.property("description", &AgriMachineBasicInfo::description)
			(rttr::metadata("display", "描述"))
		.property("link", &AgriMachineBasicInfo::link)
			(rttr::metadata("display", "链接"))
		.property("length", &AgriMachineBasicInfo::length)
			(rttr::metadata("display", "长度"), 
				rttr::metadata("unit", "mm"))
		.property("span", &AgriMachineBasicInfo::span)
			(rttr::metadata("display", "宽度"),	
				rttr::metadata("unit", "mm"))
		.property("height", &AgriMachineBasicInfo::height)
			(rttr::metadata("display", "高度"), 
				rttr::metadata("unit", "mm"))
		;

	rttr::registration::class_<AgriMachineSubsoilerInfo>("AgriMachineSubsoilerInfo")
		.constructor<>()
		.property("structural_weight", &AgriMachineSubsoilerInfo::structural_weight)
			(rttr::metadata("display", "结构质量"), 
				rttr::metadata("unit", "kg"))
		.property("power_supply", &AgriMachineSubsoilerInfo::power_supply)
			(rttr::metadata("display", "配套动力"), 
				rttr::metadata("unit", "KW"))
		.property("blade_type", &AgriMachineSubsoilerInfo::blade_type)
			(rttr::metadata("display", "深松铲结构形式"), 
				rttr::metadata("isEnum", true))
		.property("blade_num", &AgriMachineSubsoilerInfo::blade_num)
			(rttr::metadata("display", "深松铲数量"),
				rttr::metadata("unit", "个"))
		.property("work_width", &AgriMachineSubsoilerInfo::work_width)
			(rttr::metadata("display", "工作幅宽"),
				rttr::metadata("unit", "cm"))
		.property("blade_space", &AgriMachineSubsoilerInfo::blade_space)
			(rttr::metadata("display", "铲间距"),
				rttr::metadata("unit", "cm"))
		.property("plough_depth", &AgriMachineSubsoilerInfo::plough_depth)
			(rttr::metadata("display", "耕深"),
				rttr::metadata("unit", "cm"))
		.property("operate_speed", &AgriMachineSubsoilerInfo::operate_speed)
			(rttr::metadata("display", "作业速度"),
				rttr::metadata("unit", "km/h"))
		.property("operate_hourly_rate", &AgriMachineSubsoilerInfo::operate_hourly_rate)
			(rttr::metadata("display", "作业小时生产率"),
				rttr::metadata("unit", "hm2/h"))
		;

	rttr::registration::class_<AgriMachineTractorsInfo>("AgriMachineTractorsInfo")
		.constructor<>()
		.property("weight_max", &AgriMachineTractorsInfo::weight_max)
			(rttr::metadata("display", "最大配重质量前/后"),
				rttr::metadata("unit", "kg"))
		.property("engine_type", &AgriMachineTractorsInfo::engine_type)
			(rttr::metadata("display", "发动机型号"))
		.property("engine_pattern", &AgriMachineTractorsInfo::engine_pattern)
			(rttr::metadata("display", "发送机型式"))
		.property("engine_rated_power", &AgriMachineTractorsInfo::engine_rated_power)
			(rttr::metadata("display", "发动机标定功率"),
				rttr::metadata("unit", "KW"))
		.property("engine_rated_speed", &AgriMachineTractorsInfo::engine_rated_speed)
			(rttr::metadata("display", "发动机额定转速"),
				rttr::metadata("unit", "r/min"))
		.property("clutch", &AgriMachineTractorsInfo::clutch)
			(rttr::metadata("display", "离合器"))
		.property("gearbox", &AgriMachineTractorsInfo::gearbox)
			(rttr::metadata("display", "变速箱"))
		.property("front_wheel", &AgriMachineTractorsInfo::front_wheel)
			(rttr::metadata("display", "前轮速度范围"),
				rttr::metadata("unit", "km/h"))
		.property("rear_wheel", &AgriMachineTractorsInfo::rear_wheel)
			(rttr::metadata("display", "后轮速度范围"),
				rttr::metadata("unit", "km/h"))
		.property("front_wheel_pitch_adjust", &AgriMachineTractorsInfo::front_wheel_pitch_adjust)
			(rttr::metadata("display", "前轮规格"))
		.property("rear_wheel_pitch_adjust", &AgriMachineTractorsInfo::rear_wheel_pitch_adjust)
			(rttr::metadata("display", "后轮规格"))
		.property("min_ground_clearance", &AgriMachineTractorsInfo::min_ground_clearance)
			(rttr::metadata("display", "最小离地间隙"),
				rttr::metadata("unit", "mm"))
		.property("min_turn_radius", &AgriMachineTractorsInfo::min_turn_radius)
			(rttr::metadata("display", "最小转向圆半径"),
				rttr::metadata("unit", "m"))
		.property("pto_shaft", &AgriMachineTractorsInfo::ptos_shaft)
			(rttr::metadata("display", "动力输出轴形式"),
				rttr::metadata("isEnum", true))
		.property("pto_speed", &AgriMachineTractorsInfo::pto_speed)
			(rttr::metadata("display", "动力输出轴转速"),
				rttr::metadata("unit", "r/min"))
		.property("pto_power", &AgriMachineTractorsInfo::pto_power)
			(rttr::metadata("display", "动力输出轴功率"),
				rttr::metadata("unit", "KW"))
		.property("tilling_depth_control", &AgriMachineTractorsInfo::tilling_depth_control)
			(rttr::metadata("display", "耕深控制方式"))
		;

	rttr::registration::class_<AgriMachineGraderInfo>("AgriMachineGraderInfo")
		.constructor<>()
		.property("structural_style", &AgriMachineGraderInfo::structural_style)
			(rttr::metadata("display", "结构型式"))
		.property("max_work_width", &AgriMachineGraderInfo::max_work_width)
			(rttr::metadata("display", "最大工作幅宽"),
				rttr::metadata("unit", "mm"))
		.property("match_power_range", &AgriMachineGraderInfo::match_power_range)
			(rttr::metadata("display", "配套拖拉机功率范围"),
				rttr::metadata("unit", "kW"))
		.property("control_mode", &AgriMachineGraderInfo::control_mode)
			(rttr::metadata("display", "控制方式"))
		.property("shovel_type", &AgriMachineGraderInfo::shovel_type)
			(rttr::metadata("display", "平地铲型式"))
		.property("shovel_structure", &AgriMachineGraderInfo::shovel_structure)
			(rttr::metadata("display", "平地铲结构"))
		.property("shovel_blade_length", &AgriMachineGraderInfo::shovel_blade_length)
			(rttr::metadata("display", "平地铲铲刃长度"),
				rttr::metadata("unit", "mm"))
		.property("shovel_blade_height", &AgriMachineGraderInfo::shovel_blade_height)
			(rttr::metadata("display", "平地铲高度"),
				rttr::metadata("unit", "mm"))
		.property("shovel_max_lift_height", &AgriMachineGraderInfo::shovel_max_lift_height)
			(rttr::metadata("display", "平地铲最大提升高度"),
				rttr::metadata("unit", "mm"))
		.property("computer_mode", &AgriMachineGraderInfo::computer_mode)
			(rttr::metadata("display", "车载计算机型号"))
		.property("satellite_receiver_diff_system", &AgriMachineGraderInfo::satellite_receiver_diff_system)
			(rttr::metadata("display", "卫星接收机差分系统"))
		.property("satellite_receiver_model", &AgriMachineGraderInfo::satellite_receiver_model)
			(rttr::metadata("display", "卫星接收机型号"))
		.property("satellite_signal_source", &AgriMachineGraderInfo::satellite_signal_source)
			(rttr::metadata("display", "卫星接收机接收信号源"))
		.property("satellite_antennas_num", &AgriMachineGraderInfo::satellite_antennas_num)
			(rttr::metadata("display", "卫星天线数量"))
		.property("radio_trans_frequency", &AgriMachineGraderInfo::radio_trans_frequency)
			(rttr::metadata("display", "移动基站无线电发射设备频率"),
				rttr::metadata("unit", "Hz"))
		.property("radio_trans_power", &AgriMachineGraderInfo::radio_trans_power)
			(rttr::metadata("display", "移动基站无线电发射设备功率"),
				rttr::metadata("unit", "W"))
		.property("controller", &AgriMachineGraderInfo::controller)
			(rttr::metadata("display", "控制器型号"))
		.property("hydraulic_pump", &AgriMachineGraderInfo::hydraulic_pump)
			(rttr::metadata("display", "液压泵型号"))
		.property("distributor", &AgriMachineGraderInfo::distributor)
			(rttr::metadata("display", "分配器型号"))
		.property("oil_cylinder", &AgriMachineGraderInfo::oil_cylinder)
			(rttr::metadata("display", "油缸型号规格"))
		.property("oil_cylinder_num", &AgriMachineGraderInfo::oil_cylinder_num)
			(rttr::metadata("display", "油缸数量"),
				rttr::metadata("unit", "个"))
		.property("tire", &AgriMachineGraderInfo::tire)
			(rttr::metadata("display", "轮胎型号规格"))
		.property("tire_num", &AgriMachineGraderInfo::tire_num)
			(rttr::metadata("display", "轮胎数量"),
				rttr::metadata("unit", "个"))
		.property("trans_gap", &AgriMachineGraderInfo::trans_gap)
			(rttr::metadata("display", "运输间隙（悬挂式不测）"),
				rttr::metadata("unit", "mm"))
		;

	rttr::registration::class_<AgriMachineSeederInfo>("AgriMachineSeederInfo")
		.constructor<>()
		.property("line_space", &AgriMachineSeederInfo::line_space)
			(rttr::metadata("display", "行距"),
				rttr::metadata("unit", "mm"))
		.property("work_lines", &AgriMachineSeederInfo::work_lines)
			(rttr::metadata("display", "工作行数"),
				rttr::metadata("unit", "行"))
		.property("work_width", &AgriMachineSeederInfo::work_width)
			(rttr::metadata("display", "工作幅宽"),
				rttr::metadata("unit", "cm"))
		.property("seed_dispenser_type", &AgriMachineSeederInfo::seed_dispenser_type)
			(rttr::metadata("display", "排种器形式"))
		.property("seed_dispenser_num", &AgriMachineSeederInfo::seed_dispenser_num)
			(rttr::metadata("display", "排种器数量"),
				rttr::metadata("unit", "个"))
		.property("fertilizer_distributor_type", &AgriMachineSeederInfo::fertilizer_distributor_type)
			(rttr::metadata("display", "排肥器形式"))
		.property("fertilizer_distributor_num", &AgriMachineSeederInfo::fertilizer_distributor_num)
			(rttr::metadata("display", "排肥器数量"),
				rttr::metadata("unit", "个"))
		.property("trans_mechanism_type", &AgriMachineSeederInfo::trans_mechanism_type)
			(rttr::metadata("display", "传动机构形式"))
		.property("trencher_type", &AgriMachineSeederInfo::trencher_type)
			(rttr::metadata("display", "开沟器形式"))
		.property("anti_block_type", &AgriMachineSeederInfo::anti_block_type)
			(rttr::metadata("display", "防堵工作部件形式"))
		;

	rttr::registration::class_<AgriMachineHarvesterInfo>("AgriMachineHarvesterInfo")
		.constructor<>()
		.property("structural_style", &AgriMachineHarvesterInfo::structural_style)
			(rttr::metadata("display", "结构型式"))
		.property("whole_weight", &AgriMachineHarvesterInfo::whole_weight)
			(rttr::metadata("display", "整机质量"),
				rttr::metadata("unit", "kg"))
		.property("minimum_gap", &AgriMachineHarvesterInfo::minimum_gap)
			(rttr::metadata("display", "最小离地间隙"),
				rttr::metadata("unit", "mm"))
		.property("work_speed", &AgriMachineHarvesterInfo::work_speed)
			(rttr::metadata("display", "作业速度"),
				rttr::metadata("unit", "km/h"))
		.property("productivity_per_hour", &AgriMachineHarvesterInfo::productivity_per_hour)
			(rttr::metadata("display", "作业小时生产率"),
				rttr::metadata("unit", "hm2/h"))
		.property("fuel_consume_per_unit", &AgriMachineHarvesterInfo::fuel_consume_per_unit)
			(rttr::metadata("display", "单位作业量燃油消耗量"),
				rttr::metadata("unit", "kg/hm2"))
		.property("header_width", &AgriMachineHarvesterInfo::header_width)
			(rttr::metadata("display", "割台宽度"),
				rttr::metadata("unit", "mm"))
		.property("feed_quantity", &AgriMachineHarvesterInfo::feed_quantity)
			(rttr::metadata("display", "喂入量"),
				rttr::metadata("unit", "kg/s"))
		.property("cut_knife_type", &AgriMachineHarvesterInfo::cut_knife_type)
			(rttr::metadata("display", "割刀型式"))
		.property("header_auger_type", &AgriMachineHarvesterInfo::header_auger_type)
			(rttr::metadata("display", "割台搅龙型式"))
		.property("thresh_wheel_type", &AgriMachineHarvesterInfo::thresh_wheel_type)
			(rttr::metadata("display", "拨禾轮型式"))
		.property("thresh_wheel_diameter", &AgriMachineHarvesterInfo::thresh_wheel_diameter)
			(rttr::metadata("display", "拨禾轮直径"),
				rttr::metadata("unit", "mm"))
		.property("thresh_wheel_board_num", &AgriMachineHarvesterInfo::thresh_wheel_board_num)
			(rttr::metadata("display", "拨禾轮板数"),
				rttr::metadata("unit", "个"))
		.property("drum_layout", &AgriMachineHarvesterInfo::drum_layout)
			(rttr::metadata("display", "脱粒机构布置方式"))
		.property("drum_num", &AgriMachineHarvesterInfo::drum_num)
			(rttr::metadata("display", "脱粒滚筒数量"),
				rttr::metadata("unit", "个"))
		.property("main_drum_type", &AgriMachineHarvesterInfo::main_drum_type)
			(rttr::metadata("display", "脱粒滚筒主滚筒型式"))
		.property("main_drum_dimensions", &AgriMachineHarvesterInfo::main_drum_dimensions)
			(rttr::metadata("display", "脱粒滚筒主滚筒尺寸(外径×长度)"),
				rttr::metadata("unit", "mm"))
		.property("auxiliary_drum_dimensions", &AgriMachineHarvesterInfo::auxiliary_drum_dimensions)
			(rttr::metadata("display", "脱粒滚筒副滚筒尺寸(外径×长度)"),
				rttr::metadata("unit", "mm"))
		.property("concave_plate_screen", &AgriMachineHarvesterInfo::concave_plate_screen)
			(rttr::metadata("display", "凹板筛型式"))
		.property("fans_type", &AgriMachineHarvesterInfo::fans_type)
			(rttr::metadata("display", "风扇型式"))
		.property("fans_diameter", &AgriMachineHarvesterInfo::fans_diameter)
			(rttr::metadata("display", "风扇直径"),
				rttr::metadata("unit", "mm"))
		.property("fans_num", &AgriMachineHarvesterInfo::fans_num)
			(rttr::metadata("display", "风扇数量"))
		.property("drive_mode", &AgriMachineHarvesterInfo::drive_mode)
			(rttr::metadata("display", "驱动方式"))
		.property("guide_wheel_tires", &AgriMachineHarvesterInfo::guide_wheel_tires)
			(rttr::metadata("display", "导向轮轮胎规格"))
		.property("drive_wheel_tires", &AgriMachineHarvesterInfo::drive_wheel_tires)
			(rttr::metadata("display", "驱动轮轮胎规格"))
		.property("guide_wheel_track", &AgriMachineHarvesterInfo::guide_wheel_track)
			(rttr::metadata("display", "导向轮轮距"),
				rttr::metadata("unit", "mm"))
		.property("drive_wheel_track", &AgriMachineHarvesterInfo::drive_wheel_track)
			(rttr::metadata("display", "驱动轮轮距"),
				rttr::metadata("unit", "mm"))
		.property("wheel_base", &AgriMachineHarvesterInfo::wheel_base)
			(rttr::metadata("display", "轴距"),
				rttr::metadata("unit", "mm"))
		.property("work_gear", &AgriMachineHarvesterInfo::work_gear)
			(rttr::metadata("display", "作业档位"))
		.property("cab_type", &AgriMachineHarvesterInfo::cab_type)
			(rttr::metadata("display", "驾驶室类型"))
		.property("gearbox_type", &AgriMachineHarvesterInfo::gearbox_type)
			(rttr::metadata("display", "变速箱型式"))
		.property("brake_type", &AgriMachineHarvesterInfo::brake_type)
			(rttr::metadata("display", "制动器型式"))
		.property("drive_axle_type", &AgriMachineHarvesterInfo::drive_axle_type)
			(rttr::metadata("display", "驱动桥型式"))
		.property("stem_chopper_type", &AgriMachineHarvesterInfo::stem_chopper_type)
			(rttr::metadata("display", "茎秆切碎器型式"))
		.property("auto_unload", &AgriMachineHarvesterInfo::auto_unload)
			(rttr::metadata("display", "机械自动卸粮"))
		;
}