#ifndef LY_AGRIMACHINEMANAGER_GLOBAL_H_
#define LY_AGRIMACHINEMANAGER_GLOBAL_H_
 
#include <QtCore/qglobal.h>

#if defined(LY_AGRIMACHNIEMANAGER_LIBRARY)
#  define LY_AGRIMACHNIEMANAGERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define LY_AGRIMACHNIEMANAGERSHARED_EXPORT Q_DECL_IMPORT
#endif
#endif  // LY_AgriMachineManager_global_H