QT += positioning

HEADERS += \
    $$PWD/Mavlink_Control.h \
    $$PWD/QGCTemporaryFile.h

SOURCES += \
    $$PWD/Mavlink_Control.cpp \
    $$PWD/QGCTemporaryFile.cc


# DEFINES += LY_PROTOCOLPARSE_XYGSSERVER_IPROTOCOLPARSEXYGSSERVERIMPL_MAVLINK_CONTROL_SEND_MESSAGE

DEFINES += LY_PROTOCOLPARSE_XYGSSERVER_IPROTOCOLPARSEXYGSSERVERIMPL_MAVLINK_CONTROL_RECV_MESSAGE
DEFINES += LY_PROTOCOLPARSE_XYGSSERVER_IPROTOCOLPARSEXYGSSERVERIMPL_MAVLINK_CONTROL_SEND_MESSAGE
