#ifndef LY_FIRESPREADSERVIVE_GLOBAL_H
#define LY_FIRESPREADSERVIVE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LY_FIRESPREADSERVIVE_LIBRARY)
#define LY_FIRESPREADSERVIVESHARED_EXPORT Q_DECL_EXPORT
#else
#define LY_FIRESPREADSERVIVESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif
