#ifndef LY_AGROTASKMANAGE_GLOBAL_H
#define LY_AGROTASKMANAGE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LY_AGROTASKMANAGE_LIBRARY)
    #define LY_AGROTASKMANAGESHARED_EXPORT Q_DECL_EXPORT
#else
    #define LY_AGROTASKMANAGESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // LY_TASKMANAGE_GLOBAL_H
