#ifndef LY_UAVNAVIGATIONARMSHOTALONEFIREPROT_GLOBAL_H
#define LY_UAVNAVIGATIONARMSHOTALONEFIREPROT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LY_UAVNAVIGATIONARMSHOTALONEFIREPROT_LIBRARY)
#  define LY_UAVNAVIGATIONARMSHOTALONEFIREPROTSHARED_EXPORT Q_DECL_EXPORT
#else
#  define LY_UAVNAVIGATIONARMSHOTALONEFIREPROTSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif
