#ifndef LY_CONFIGBUNDLECONTROLSERVICE_GLOBAL_H
#define LY_CONFIGBUNDLECONTROLSERVICE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LY_CONFIGBUNDLECONTROLSERVICE_LIBRARY)
    #define LY_CONFIGBUNDLECONTROLSERVICESHARED_EXPORT Q_DECL_EXPORT
#else
    #define LY_CONFIGBUNDLECONTROLSERVICESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif
