#ifndef LY_SYSTEMMAINTENANCESERVICE_GLOBAL_H
#define LY_SYSTEMMAINTENANCESERVICE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LY_SYSTEMMAINTENANCESERVICE_LIBRARY)
    #define LY_SYSTEMMAINTENANCESERVICESHARED_EXPORT Q_DECL_EXPORT
#else
    #define LY_SYSTEMMAINTENANCESERVICESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif
