
#ifndef LY_AGRISPRAYPRESCRIPTION_GLOBAL_H
#define LY_AGRISPRAYPRESCRIPTION_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LY_AGRISPRAYPRESCRIPTION_LIBRARY)
#define LY_AGRISPRAYPRESCRIPTIONSHARED_EXPORT Q_DECL_EXPORT
#else
#define LY_AGRISPRAYPRESCRIPTIONSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // LY_AGRISPRAYPRESCRIPTIONPLOUGH_GLOBAL_H
